<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.1</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>XavierJefferson</Authors>
    <Copyright>2025</Copyright>
    <PackageProjectUrl>https://github.com/xavierjefferson/XavierJefferson.JsonPathParser</PackageProjectUrl>
    <RepositoryUrl>https://github.com/xavierjefferson/XavierJefferson.JsonPathParser</RepositoryUrl>
    <PackageTags>jsonpath c#</PackageTags>
    <PackageReleaseNotes>Initial release</PackageReleaseNotes>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <Description>A .NET domain specific language for reading JSON documents.</Description>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="json-path-assert\**" />
    <EmbeddedResource Remove="json-path-assert\**" />
    <None Remove="json-path-assert\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\license.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="newtonsoft.json" Version="13.0.3" />
    <PackageReference Include="nito.asyncex" Version="5.1.2" />
    <PackageReference Include="System.runtime.caching" Version="8.0.0" />
  </ItemGroup>

</Project>
